### ISSUE TITLE
Many messages types fail to parse to JSON due to message database errors.

### ISSUE THREAD

**Issue by roamingryan** [novatel/novatel_edie#2]
As currently released (d212681f1952704e50e9c8977891dd024c3338ae), the library is unable to parse many of the most widely used OEM log messages.  **The root cause appears to be duplicate field names in the [message database file](https://github.com/novatel/novatel_edie/blob/main/database/novatel_log_definitions.json).** These duplicate names result in fields being overwritten as the JSON output is generated.

The follow message types are incompletely parsed:
```
ALIGNBSLNENU
ALIGNBSLNXYZ
BESTGNSSPOS
BESTGNSSVEL
BESTPOS
BESTUTM
BESTVEL
BESTVELX
BESTXYZ
BSLNXYZ
CLOCKMODEL
DATUMTRANSFORMATIONS
DUALANTENNAHEADING
GLOEPHEMERIS
GPGGA
GPGGALONG
GPGRS
GPGSA
GPHDT
GPHDTDUALANTENNA
HEADING2
HEADINGRATE
INSCONFIG
INSPVAX
INSVELUSER
MASTERPOS
MATCHEDPOS
MATCHEDXYZ
PDPPOS
PDPVEL
PDPXYZ
PPPPOS
PSRPOS
PSRVEL
PSRXYZ
QZSSEPHEMERIS
ROVERPOS
RTKPOS
RTKVEL
RTKXYZ
SATEL9INFO
SATXYZ2
SBAS25
TILTSTATUS
TSS1
```

### Example

`BESTXYZ` is a good example of a message that fails to parse completely.  Given this input message from an OEM7 receiver:

```
#BESTXYZA,COM2,0,83.0,FINE,2224,420105.000,02a40000,44cf,16407;SOL_COMPUTED,SINGLE,-1286545.8180,-4720990.4770,4079927.8880,1.8344,3.8956,3.7563,SOL_COMPUTED,DOPPLER_VELOCITY,-0.0088,0.0278,-0.0261,0.2193,0.4656,0.4490,"",0.000,0.000,0.000,9,7,7,7,0,06,00,03*710498e8
```

EDIE produces the following JSON outputs for the header and body of the message.

Header: (this looks fine)
```json
{"IdleTime":83.0,"MessageFormat":1,"MessageId":241,"MessageLength":276,"MessageName":"BESTXYZ","MessageSource":0,"MessageTime":420105000,"MessageTimeStatus":160,"MessageWeek":2224,"ReceiverSWVersion":16407,"ReceiverStatus":44302336,"ReponseID":0,"SequenceNumber":0,"port":0}
```

Body: (this has errors)
```json
{"eMyPositionStatus":"SOL_COMPUTED","eMyPositionType":"SINGLE","dMyX":-0.0088,"dMyY":0.0278,"dMyZ":-0.0261,"fMyXStdDev":0.21930000185966492,"fMyYStdDev":0.46560001373291016,"fMyZStdDev":0.4490000009536743,"eMyStatus":"SOL_COMPUTED","eMyType":"DOPPLER_VELOCITY","acMyBaseID":"","fMyLatency":0.0,"fMyDifferentialLag":0.0,"fMySolutionAge":0.0,"ucMyNumTracked":0,"ucMyNumInSolution":0,"ucMyNumInSolutionSingleFreq":0,"ucMyNumInSolutionDualFreq":0,"cCharAsInt":0,"ucMyExtendedSolutionStatus":0,"ucMyGALandBDSSignals":0,"ucMyGPSandGLOSignals":0}
```
Note that the ECEF XYZ position components have switched from "-1286545.8180,-4720990.4770,4079927.8880" to "-0.0088, 0.0278, -0.0261".  Those are the ECEF velocity parameters and the position parameters are completely lost. This appears to stem from reuse of field names in the message definition database.

This problem is widespread and affects 45 different message types. Here is a list of the [messages with duplicate fields](https://github.com/novatel/novatel_edie/files/9449270/messages_with_duplicate_fields.txt), which was generated with this simple Python script:

```python
import json
import sys

def check_db(fn):
    with open(fn, 'r') as f:
        db = json.load(f)
    print("Loaded {} message definitions".format(len(db)))
    for msg in db:
        has_dupes = False
        s = "Msg {} has duplicate fields\n".format(msg["name"])
        fields = set()
        field_num = 0
        for f in msg["fields"]:
            name = f["name"]
            if name in fields:
                has_dupes = True
                s += "  field {:2}: {}\n".format(field_num,name)
            fields.add(name)
            field_num += 1
        if has_dupes:
            print(s)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <JSON DB>".format(sys.argv[0]))
        sys.exit(1)
    check_db(sys.argv[1])
```
I suspect the `novatel_message_definitions.json` file is machine generated, so I am going to hold off on issuing a pull request with manual fixes.

**Comment by novatel-applications-engineering** [comment]
Thank you for your contribution and effort in this issue. I wanted to update you that this issue has already been addressed in the latest version of EDIE.
